### Register customer
POST http://localhost:8082/customers/register
Content-Type: application/json
Accept: application/json

{
  "name": "Oliver Zihler"
}
> {%
    const response = JSON.parse(response.body);
    client.global.set("customerId", response.id);
%}
