### Place order
POST http://localhost:8081/orders?customerId={{customerId}}&amount=15.5
Content-Type: application/json
Accept: application/json

### Get customer after order
GET http://localhost:8082/customers/{{customerId}}
Accept: application/json
